[package]
name = "indielinks-test"
version = "0.0.1"
edition = "2021"

[dependencies]
indielinks = { path = "../indielinks" }
inventory = "0.3.17"
lazy_static = "1.5.0"
libtest-mimic = "0.8.1"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0.217", features = ["serde_derive"] }
serde_toml = "0.0.1"
snafu = { version = "0.8.5", features = ["backtrace"] }
tap = "1.0.1"
toml = "0.8.19"

[[test]]
name = "delicious-alternator"
harness = false

[[test]]
name = "delicious-scylla"
harness = false
