no-setup = true
no-teardown = true
# The URL at which indielinks can be reached from within a test
url = "http://localhost:20673"
# The origin to use in forming AP identifiers
indielinks = "http://indiemark.local:20673"
username = "sp1ff"
api_key = "6caf392688cc6b164fe88b786acb6ab6ed4eda6e4b1a0c1daf09aa9da3c89873"
local_port = 32768
logging = true
log_level = "DEBUG"

[scylla]
hosts = ["127.0.0.1:9042"]

[dynamo]
location = ["http://127.0.0.1:8042", "http://127.0.0.1:8043", "http://127.0.0.1:8044"]

