no-setup = true
no-teardown = false
# The URL at which indielinks can be reached from *within* a test
indielinks = "http://indiemark.local:20673"
ops = "http://127.0.0.1:20675"
username = "sp1ff"
api_key = "6caf392688cc6b164fe88b786acb6ab6ed4eda6e4b1a0c1daf09aa9da3c89873"
logging = false
log_level = "INFO"

[raft-nodes]
"0" = { addr = "127.0.0.1:20676" }
"1" = { addr = "127.0.0.1:20679" }
"2" = { addr = "127.0.0.1:20682" }
"3" = { addr = "127.0.0.1:20685" }
"4" = { addr = "127.0.0.1:20688" }

# Regrettably, this must match exactly the indielinks configuration item of the same name
[pepper.peppers]
"pepper-ver:20250213" = [0xb2, 0x91, 0x48, 0x34, 0x4d, 0x5f, 0xd3, 0x7e, 0x59, 0x71, 0x57, 0x91, 0xdd, 0x00, 0x32, 0x92, 0x62, 0xe9, 0x19, 0x77, 0x6d, 0xae, 0x4b, 0x5b, 0x6a, 0xab, 0x00, 0x67, 0x0e, 0x8c, 0xf4, 54]

[scylla]
hosts = ["127.0.0.1:9042"]

[dynamo]
location = ["http://127.0.0.1:8042", "http://127.0.0.1:8043", "http://127.0.0.1:8044"]
