no-setup = true
no-teardown = true
# The URL at which indielinks can be reached from *within* a test'
indielinks = "http://indiemark.local:20679"
ops = "http://127.0.0.1:20680"
username = "sp1ff"
api-key = "v1:5eb56ceebb7425aafe36eabca8b923054b4907d9375acd0b9950c51b57b201fb73e437428050f451b57632f99a3bbd5bed1c0f51cc0df752147090ed26e975f4"
logging = true
log-level = "DEBUG"

[raft-nodes]
"0" = { addr = "127.0.0.1:20681" }
"1" = { addr = "127.0.0.1:20684" }
"2" = { addr = "127.0.0.1:20687" }
"3" = { addr = "127.0.0.1:20690" }
"4" = { addr = "127.0.0.1:20693" }

# Regrettably, this must match exactly the indielinks configuration item of the same name
[pepper.peppers]
"pepper-ver:20250213" = [0xb2, 0x91, 0x48, 0x34, 0x4d, 0x5f, 0xd3, 0x7e, 0x59, 0x71, 0x57, 0x91, 0xdd, 0x00, 0x32, 0x92, 0x62, 0xe9, 0x19, 0x77, 0x6d, 0xae, 0x4b, 0x5b, 0x6a, 0xab, 0x00, 0x67, 0x0e, 0x8c, 0xf4, 54]

[scylla]
hosts = ["127.0.0.1:9043"]

[dynamo]
location = ["http://127.0.0.1:8043", "http://127.0.0.1:8044", "http://127.0.0.1:8045"]

