version = "1"
log-file = "/tmp/indielinks.log"
public-address = "0.0.0.0:20673"
private-address = "127.0.0.1:48351"
domain = "indiemark.sh"

[storage_config.Dynamo]
location = ["http://127.0.0.1:8042", "http://127.0.0.1:8043", "http://127.0.0.1:8044"]

[pepper.peppers]
"pepper-ver:20250213" = [0x47, 0x10, 0x38, 0x77, 0x16, 0x1f, 0x15, 0x62, 0x32, 0xf1, 0x58, 0xcc, 0x75, 0xfa, 0x7b, 0x5c]
