no-setup = false
no-teardown = false
url = "http://localhost:20673"
username = "sp1ff"
api_key = "6caf392688cc6b164fe88b786acb6ab6ed4eda6e4b1a0c1daf09aa9da3c89873"

[scylla]
hosts = ["127.0.0.1:9042"]

[dynamo]
location = ["http://127.0.0.1:8042", "http://127.0.0.1:8043", "http://127.0.0.1:8044"]
