version = "1"
log-file = "/tmp/indielinks.log"
public-address = "0.0.0.0:20673"
private-address = "127.0.0.1:48351"
domain = "indiemark.sh"

[storage_config.Dynamo]
location = ["http://127.0.0.1:8042", "http://127.0.0.1:8043", "http://127.0.0.1:8044"]
