[package]
name = "indielinks-cache"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
bpaf = { version = "0.9.20", features = ["bright-color"] }
http = "1.3.1"
openraft = { version = "0.9.18", features = ["serde", "storage-v2"] }
reqwest = { version = "0.12.18", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.140"
snafu = { version = "0.8.5", features = ["backtrace"] }
tap = "1.0.1"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "signal"] }
tower-http = { version = "0.6.4", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["ansi", "env-filter"] }
url = "2.5.4"
uuid = { version = "1.17.0", features = ["v4"] }
