[workspace]
members = ["indielinks", "indielinks-cache", "indielinks-cache-test", "indielinks-test"]
resolver = "2"

[patch.crates-io]
# openraft = { version = "=0.9.20", path = "../openraft/openraft" }
picky = { path = "../picky-rs-sp1ff/picky" }
