[package]
name = "indielinks"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = { version = "0.7.9", features = ["tracing"] }
clap = { version = "4.5.23", features = ["cargo", "env"] }
errno = "0.3.10"
lazy_static = "1.5.0"
libc = "0.2.169"
opentelemetry = "0.27.1"
opentelemetry-prometheus = "0.27.0"
opentelemetry_sdk = "0.27.1"
prometheus = "0.13.4"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.216", features = ["derive"] }
snafu = "0.8.5"
tokio = { version = "1.42.0", features = ["rt-multi-thread", "signal", "sync"] }
toml = "0.8.19"
tower-http = { version = "0.6.2", features = ["auth", "cors", "set-header", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
